apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  namespace: prisma
  labels:
    stage: production
    name: prisma
    app: prisma
data:
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: postgres
        migrations: true
        host: database
        port: 5432
        user: prisma
        password: prisma
        rawAccess: true
        # schema: default$default
        # database: prisma
        rawAccess: true
