apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prisma
  namespace: prisma
  labels:
    stage: production
    name: prisma
    app: prisma
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        stage: production
        name: prisma
        app: prisma
    spec:
      containers:
      - env:
        - name: PRISMA_CONFIG
          valueFrom:
            configMapKeyRef:
              name: prisma-configmap
              key: PRISMA_CONFIG
        image: prismagraphql/prisma:1.28
        name: prisma
        ports:
        - containerPort: 4466
        resources: {}
      restartPolicy: Always
status: {}
