apiVersion: v1
kind: Service
metadata:
  name: prisma
  namespace: prisma
spec:
  ports:
  - name: "4466"
    port: 4466
    targetPort: 4466
  selector:
    stage: production
    name: prisma
    app: prisma
status:
  loadBalancer: {}
