apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-disk
  namespace: prisma
  labels:
    stage: production
    name: database
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
